<template>
  <div>
    <img
      :src="require('@/app/assets/icons/dummy.svg')"
      alt="dummy"
    >
    <img
      :src="require('~/app/assets/icons/dummy.svg')"
      alt="dummy"
    >
  </div>
</template>
