name: trigger-sync

on:
  pull_request:
    branches:
      # - "epic-*"
      - "**"
    types:
      - closed
    paths:
      - "**"
      # - "src/app/**"
      # - "!**.mdx"
      # - "!**.mock.json"
      # - "!**.stories.js"

env:
  COPY_REPOSITORY: shota-kamezawa/copy_repository
  WORKFLOW_ID: sync.yml

jobs:
  trigger-sync:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Workflow dispatch
        run: |
          curl -i -X POST \
            -H "Authorization: token ${{ secrets.SYNC_REPOSITORY }}" \
            -H "Content-Type: application/vnd.github.v3+json" \
            -d '{"pr_number": ${{ github.event.pull_request.number }}}' \
            https://api.github.com/repos/${{ env.COPY_REPOSITORY }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches
